CUDA_DIR := /usr/local/cuda-7.5

CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
-gencode arch=compute_20,code=sm_21 \
-gencode arch=compute_30,code=sm_30 \
-gencode arch=compute_35,code=sm_35 \
-gencode arch=compute_50,code=sm_50 \
-gencode arch=compute_50,code=compute_50

BLAS := open

BLAS_INCLUDE := /home/fan6/deep_package/OpenBLAS/install/include
BLAS_LIB := /home/fan6/deep_package/OpenBLAS/install/lib

PYTHON_INCLUDE := /usr/include/python2.7 /usr/lib64/python2.7/dist-packages/numpy/core/include

INCLUDE_DIRS := /home/fan6/deep_package/protobuf/install/include $(PYTHON_INCLUDE) /usr/local/include 

LIBRARY_DIRS := . /home/fan6/deep_package/protobuf/install/lib $(PYTHON_LIB) /usr/local/lib /usr/lib64

BUILD_DIR := build

DISTRIBUTE_DIR := distribute

TEST_GPUID := 0
